-- Migration 31: Add moon defense and ship columns plus energy tracking
BEGIN;

ALTER TABLE moons
    ADD COLUMN IF NOT EXISTS energy INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_resource_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS rocket_launcher INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS light_laser INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS heavy_laser INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gauss_cannon INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ion_cannon INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS plasma_turret INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS small_shield_dome INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS large_shield_dome INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS small_cargo INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS large_cargo INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS light_fighter INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS heavy_fighter INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cruiser INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS battleship INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS colony_ship INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS recycler INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS espionage_probe INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bomber INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS destroyer INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS deathstar INTEGER DEFAULT 0;

COMMIT;
