-- Authoritative universe membership, coordinate allocation, and score state.

CREATE TABLE IF NOT EXISTS universes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    speed INTEGER NOT NULL CHECK (speed > 0),
    registration_open BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- A fresh installation always has somewhere for server-side registration to
-- place a player. Existing installations keep their operator-managed rows.
INSERT INTO universes (id, name, speed, registration_open)
SELECT 1, 'Universus Prime', 1, TRUE
WHERE NOT EXISTS (SELECT 1 FROM universes)
ON CONFLICT DO NOTHING;

DO $$
DECLARE
    sequence_name TEXT;
    maximum_id BIGINT;
BEGIN
    sequence_name := pg_get_serial_sequence('universes', 'id');
    SELECT MAX(id) INTO maximum_id FROM universes;
    IF sequence_name IS NOT NULL AND maximum_id IS NOT NULL THEN
        PERFORM setval(sequence_name, maximum_id, TRUE);
    END IF;
END $$;

ALTER TABLE users ADD COLUMN IF NOT EXISTS universe_id BIGINT;
UPDATE users
SET universe_id = (SELECT id FROM universes ORDER BY id LIMIT 1)
WHERE universe_id IS NULL;
ALTER TABLE users ALTER COLUMN universe_id SET NOT NULL;

DO $$
DECLARE
    default_universe BIGINT;
BEGIN
    SELECT id INTO default_universe FROM universes ORDER BY id LIMIT 1;
    EXECUTE format(
        'ALTER TABLE users ALTER COLUMN universe_id SET DEFAULT %s',
        default_universe
    );
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'users_universe_id_fkey'
          AND conrelid = 'users'::regclass
    ) THEN
        ALTER TABLE users
            ADD CONSTRAINT users_universe_id_fkey
            FOREIGN KEY (universe_id) REFERENCES universes(id) ON DELETE RESTRICT;
    END IF;
END $$;

ALTER TABLE planets ADD COLUMN IF NOT EXISTS universe_id BIGINT;
UPDATE planets AS p
SET universe_id = u.universe_id
FROM users AS u
WHERE u.id = p.user_id AND p.universe_id IS NULL;
ALTER TABLE planets ALTER COLUMN universe_id SET NOT NULL;

DO $$
DECLARE
    default_universe BIGINT;
BEGIN
    SELECT id INTO default_universe FROM universes ORDER BY id LIMIT 1;
    EXECUTE format(
        'ALTER TABLE planets ALTER COLUMN universe_id SET DEFAULT %s',
        default_universe
    );
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'planets_universe_id_fkey'
          AND conrelid = 'planets'::regclass
    ) THEN
        ALTER TABLE planets
            ADD CONSTRAINT planets_universe_id_fkey
            FOREIGN KEY (universe_id) REFERENCES universes(id) ON DELETE RESTRICT;
    END IF;
END $$;

-- Coordinates may be reused between universes, never within one universe.
ALTER TABLE planets DROP CONSTRAINT IF EXISTS planets_galaxy_system_position_key;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'planets_universe_coordinates_unique'
          AND conrelid = 'planets'::regclass
    ) THEN
        ALTER TABLE planets
            ADD CONSTRAINT planets_universe_coordinates_unique
            UNIQUE (universe_id, galaxy, system, position);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_planets_universe_coordinates
    ON planets (universe_id, galaxy, system, position);
CREATE INDEX IF NOT EXISTS idx_users_universe
    ON users (universe_id, id);

-- Old accounts predate transactional registration. Backfill a score row so
-- completion processing can update every player without a special case.
INSERT INTO player_scores (user_id)
SELECT id FROM users
ON CONFLICT (user_id) DO NOTHING;

UPDATE player_scores
SET total_score = COALESCE(total_score, 0),
    economy_score = COALESCE(economy_score, 0),
    research_score = COALESCE(research_score, 0),
    military_score = COALESCE(military_score, 0),
    last_updated = COALESCE(last_updated, CURRENT_TIMESTAMP);

ALTER TABLE player_scores
    ALTER COLUMN total_score SET DEFAULT 0,
    ALTER COLUMN total_score SET NOT NULL,
    ALTER COLUMN economy_score SET DEFAULT 0,
    ALTER COLUMN economy_score SET NOT NULL,
    ALTER COLUMN research_score SET DEFAULT 0,
    ALTER COLUMN research_score SET NOT NULL,
    ALTER COLUMN military_score SET DEFAULT 0,
    ALTER COLUMN military_score SET NOT NULL,
    ALTER COLUMN last_updated SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN last_updated SET NOT NULL;
