[package]
name = "app-admin-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std", "serde"] }

[dev-dependencies]
hyper = "0.14"
serde_json = "1.0"
tower = "0.4"
