[package]
name = "app-scheduler-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
tracing = { workspace = true }
platform-events = { path = "../platform-events" }
platform-db = { path = "../platform-db" }
platform-observability = { path = "../platform-observability" }
serde_json = "1.0"
