[package]
name = "app-chat-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["time", "rt-multi-thread", "macros"] }
tracing = { workspace = true }
platform-observability = { path = "../platform-observability" }
platform-db = { path = "../platform-db" }
platform-events = { path = "../platform-events" }
serde_json = "1.0"
